### PR TITLE
Doubles parsing in Number.cs is fixed

### PR DESCRIPTION
**Pull request by giuliorm**
Regarding the issue https://github.com/izrik/FbxSharp/issues/39

### CODE REVIEW

**Comment by SimantoR** [comment]
Is this PR ready to go? Did anyone test it yet?

**Comment by giuliorm** [comment]
> Is this PR ready to go? Did anyone test it yet?

Actually I tested on my data :)

**Comment by SimantoR** [comment]
> > Is this PR ready to go? Did anyone test it yet?
> 
> Actually I tested on my data :)

I actually think the maintainer has not checked up on it for a while, I did make a [fork ](https://github.com/Open-Access-Group/FbxSharp) of it for using in Xenko game engine for cross platform support. You might wanna do the pull request there?

**Comment by giuliorm** [comment]
> > > Is this PR ready to go? Did anyone test it yet?
> > 
> > 
> > Actually I tested on my data :)
> 
> I actually think the maintainer has not checked up on it for a while, I did make a [fork ](https://github.com/Open-Access-Group/FbxSharp) of it for using in Xenko game engine for cross platform support. You might wanna do the pull request there?

Okay, I can do later. Thank you for your concern 
The problem was, that the parsed string had a lot of zeros, so the parsing had failed with an exception

**Comment by SimantoR** [comment]
> > > > Is this PR ready to go? Did anyone test it yet?
> > > 
> > > 
> > > Actually I tested on my data :)
> > 
> > 
> > I actually think the maintainer has not checked up on it for a while, I did make a [fork ](https://github.com/Open-Access-Group/FbxSharp) of it for using in Xenko game engine for cross platform support. You might wanna do the pull request there?
> 
> Okay, I can do later. Thank you for your concern
> The problem was, that the parsed string had a lot of zeros, so the parsing had failed with an exception

I have also started a gitter room to discuss things [here](https://gitter.im/OpenAccessGroup/FbxSharp?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Pull request merged**
